config/routes.rb
Spree::Core::Engine.routes.draw do
	namespace :admin do

		resources :code_groups
		resources :promotion_codes


  end
end

app/models/spree/calculator/flat_percent_per_item.rb
module Spree
	class Calculator::FlatPercentPerItem < Calculator
		preference :flat_percent, :decimal, :default => 0.0

		attr_accessible :preferred_flat_percent

		def self.description
			I18n.t(:flat_percent_per_item)
		end

		def compute(object=nil)
			return 0 if object.nil? || target_products.blank?
			item_total = object.line_items.map{|li| target_products.include?(li.product) ? li.amount : 0.0 }.sum
			value = item_total * BigDecimal(self.preferred_flat_percent.to_s) / 100.0
			(value * 100).round.to_f / 100
		end

		def target_products
			#TODO: product groups?
			self.calculable.promotion.rules.map(&:products).flatten
		end
	end
end

app/models/spree/calculator/flat_percent_per_taxon.rb
module Spree
	class Calculator::FlatPercentPerTaxon < Calculator
		preference :flat_percent, :decimal, :default => 0.0
		preference :taxon, :integer, :default => 0

		attr_accessible :preferred_flat_percent, :preferred_taxon

		def self.description
			I18n.t(:flat_percent_per_taxon)
		end

		def compute(object=nil)
			return 0 if object.nil?
			item_total = object.line_items.map{|li| li.product.taxons.map(&:id).include?(preferred_taxon) ? li.amount : 0.0 }.sum
			value = item_total * BigDecimal(self.preferred_flat_percent.to_s) / 100.0
			(value * 100).round.to_f / 100
		end

	end
end

app/models/spree/calculator/flat_rate_per_taxon.rb
module Spree
	class Calculator::FlatRatePerTaxon < Calculator
		preference :amount, :decimal, :default => 0.0
		preference :taxon, :integer, :default => 0

		attr_accessible :preferred_taxon, :preferred_amount

		def self.description
			I18n.t(:flat_rate_per_taxon)
		end

		def compute(object=nil)
			return 0 if object.nil?
			value = object.line_items.map{|li| li.product.taxons.map(&:id).include?(preferred_taxon) ? li.quantity*preferred_amount : 0.0 }.sum
			(value * 100).round.to_f / 100
		end

	end
end

app/models/spree/calculator/pay_n_get_m.rb
module Spree
	class Calculator::PayNGetM < Calculator
		preference :to_pay, :integer, :default => 1
		preference :to_get, :integer, :default => 1
		preference :taxon, :integer, :default => 0

		attr_accessible :preferred_to_get, :preferred_to_pay, :preferred_taxon

		def self.description
			I18n.t(:pay_n_get_m)
		end

		def compute(object=nil)
			return 0 if object.nil?
			return 0 if preferred_to_get.blank? || preferred_to_pay.blank? || preferred_taxon == 0
			return 0 if preferred_to_get <= preferred_to_pay

			sum = 0.0
			tx = Spree::Taxon.find preferred_taxon

			object.line_items.each do |line_item|
				if tx.products.map(&:id).include?(line_item.variant.product_id) 
					txs = (line_item.quantity / preferred_to_get).to_i
					discount_per_taxon = (preferred_to_get - preferred_to_pay) * line_item.price

					sum += txs * discount_per_taxon
				end
			end

			sum
		end

	end
end

app/models/spree/code_group.rb
module Spree
  class CodeGroup < ActiveRecord::Base
    attr_accessible :limit, :name, :promotion_id
    
    has_many :promotion_codes
    belongs_to :promotion_codes

    validates :name, :presence => true 

  end
end

app/models/spree/promotion/rules/club.rb
module Spree
  class Promotion::Rules::Club < PromotionRule

    def eligible?(order, options = {})
      return false if order.user.blank?
      return false unless order.user.respond_to?(:club?)

      order.user.club?
    end
  end
end

app/models/spree/promotion/rules/gender.rb
module Spree
  class Promotion::Rules::Gender < PromotionRule
  	preference :gender, :string, :default => 'm'

  	attr_accessible :preferred_gender

    def eligible?(order, options = {})
      return false if order.user.blank?
      return false if order.user.gender.blank?

      order.user.gender == preferred_gender
    end
  end
end

app/models/spree/promotion/rules/happy_birthday.rb
module Spree
  class Promotion::Rules::HappyBirthday < PromotionRule

    def eligible?(order, options = {})
      return false if order.user.blank?
      return false if order.user.birthdate.blank?

      order.user.birthdate == Date.today
    end
  end
end

app/models/spree/promotion/rules/item_quantity.rb
module Spree
  class Promotion::Rules::ItemQuantity < PromotionRule
    preference :quantity, :integer, :default => 10
    preference :operator, :string, :default => '>'

    attr_accessible :preferred_quantity, :preferred_operator

    OPERATORS = ['gt', 'gte']

    def eligible?(order, options = {})
      item_total = order.line_items.map(&:quantity).sum
      item_total.send(preferred_operator == 'gte' ? :>= : :>, preferred_quantity)
    end
  end
end

app/models/spree/promotion/rules/order_quantity.rb
module Spree
  class Promotion::Rules::OrderQuantity < PromotionRule
    preference :quantity, :integer, :default => 10
    preference :operator, :string, :default => '>'

    attr_accessible :preferred_quantity, :preferred_operator

    OPERATORS = ['gt', 'gte']

    def eligible?(order, options = {})
    	user = order.try(:user) || options[:user]
      return false if user.blank?
      return false if user.orders.blank?

      user.orders.complete.count.send(preferred_operator == 'gte' ? :>= : :>, preferred_quantity)
    end
  end
end

app/models/spree/promotion/rules/order_total.rb
module Spree
  class Promotion::Rules::OrderTotal < PromotionRule
    preference :amount, :decimal, :default => 100.00
    preference :operator, :string, :default => '>'

    attr_accessible :preferred_amount, :preferred_operator

    OPERATORS = ['gt', 'gte']

    def eligible?(order, options = {})
      user = order.try(:user) || options[:user]
      return false if user.blank?
      return false if user.orders.blank?

			item_total = user.orders.complete.map(&:total).sum
      item_total.send(preferred_operator == 'gte' ? :>= : :>, BigDecimal.new(preferred_amount.to_s))
    end
  end
end

app/models/spree/promotion/rules/product_buy_taxon.rb
module Spree
	class Promotion::Rules::ProductBuyTaxon < PromotionRule
		preference :taxon, :integer, :default => ''

		attr_accessible :preferred_taxon

		def eligible?(order, options = {})
			order.line_items.any?{|line_item| line_item.product.taxons.map(&:id).include?(preferred_taxon)}
		end

	end
end

app/models/spree/promotion/rules/product_buy_taxon_quantity.rb
module Spree
	class Promotion::Rules::ProductBuyTaxonQuantity < PromotionRule
		preference :taxon, :integer, :default => ''
		preference :quantity, :integer, :default => 10
		preference :operator, :string, :default => '>'

		attr_accessible :preferred_quantity, :preferred_operator, :preferred_taxon

		OPERATORS = ['gt', 'gte']

		def eligible?(order, options = {})
      item_total = 0
      order.line_items.each do |line_item|
        item_total += line_item.quantity if line_item.product.taxons.map(&:id).include?(preferred_taxon)
      end
      item_total.send(preferred_operator == 'gte' ? :>= : :>, preferred_quantity)
    end

	end
end

app/models/spree/promotion/rules/product_buy_taxon_total.rb
module Spree
	class Promotion::Rules::ProductBuyTaxonTotal < PromotionRule
		preference :taxon, :integer, :default => ''
		preference :amount, :decimal, :default => 100.00
		preference :operator, :string, :default => '>'

		attr_accessible :preferred_amount, :preferred_operator, :preferred_taxon

		OPERATORS = ['gt', 'gte']

		def eligible?(order, options = {})
      item_total = 0.0
      order.line_items.each do |line_item|
        item_total += line_item.amount if line_item.product.taxons.map(&:id).include?(preferred_taxon)
      end
      item_total.send(preferred_operator == 'gte' ? :>= : :>, BigDecimal.new(preferred_amount.to_s))
    end

	end
end

app/models/spree/promotion_code.rb
module Spree
  class PromotionCode < ActiveRecord::Base
    attr_accessible :code, :redeemed_at, :user_id, :code_group_id
    
    belongs_to :code_group
    belongs_to :user

    scope :redeemed, where("redeemed_at is not null")
    scope :free, where("redeemed_at is null")

    def redeemed?
    	!self.redeemed_at.blank?
    end

  end
end

app/models/spree/promotion_decorator.rb
Spree::Promotion.class_eval do
  has_many :code_groups

end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  def name_for_select(descendent = nil)
    self.name + " | "+ self.permalink
    
    #if self.parent_id.blank?
    #	descendent ? descendent.name : self.name
    #else
    #	'- '+self.parent.name_for_select(descendent ? descendent : self)
    #end
  end

end

app/controllers/spree/admin/code_groups_controller.rb
module Spree
  module Admin
    class CodeGroupsController < ResourceController
    	
      def index

      end
    end
  end
end

app/views/spree/admin/code_groups/index.html.erb
<%= render :partial => 'spree/admin/shared/promotions_sub_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_code_group_link">
      <p>
        <%= button_link_to t(:new_code_group), new_admin_code_group_url, { :remote => true, :icon => 'add', 'data-update' => 'new_code_group', :id => 'new_code_group_link' } %>
      </p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:code_groups) %></h1>

<div id="new_code_group"></div>

<%= image_tag 'spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>

<table class="index" id='listing_code_groups' data-hook>
  <thead>
    <tr data-hook="listing_code_groups_header">
      <th><%= t(:name) %></th>
      <th><%= t(:limit) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @code_groups.each do |code_group| %>
      <tr id="<%= spree_dom_id code_group %>" data-hook="listing_code_groups_row">
        <td><%= code_group.name %></td>
        <td><%= code_group.limit %></td>
        <td class="actions">
          <%= link_to_edit(code_group, :class => 'edit') %>
          &nbsp;
          <%= link_to_delete(code_group) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/promotions/_promotion_action.html.erb
<div class="promotion_action promotion-block <%= promotion_action.type.to_s.demodulize.underscore %>" id="<%= dom_id promotion_action %>">
  <% type_name = promotion_action.class.name.demodulize.underscore %>
  <% calculator_name = promotion_action.present? && promotion_action.respond_to?(:calculator) ? promotion_action.calculator.class.name.demodulize.underscore : '' %>
  <h6 class="promotion-title"><%= t("promotion_action_types.#{type_name}.description") %></h6>
  <%= link_to_with_icon 'icon-trash', '', spree.admin_promotion_promotion_action_path(@promotion, promotion_action), :remote => true, :method => :delete, :class => 'delete' %>
  
  <% param_prefix = "promotion[promotion_actions_attributes][#{promotion_action.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_action.id %>
  
  <% partial = lookup_context.find_all("spree/admin/promotions/actions/_#{calculator_name}").any? ? calculator_name : type_name %>
  <%= render :partial => "spree/admin/promotions/actions/#{partial}",
             :locals => { :promotion_action => promotion_action, :param_prefix => param_prefix } %>
</div>

app/views/spree/admin/promotions/actions/_flat_percent_per_taxon.html.erb
<div class="calculator-fields">

	<p class="field">
		<% field_name = "#{param_prefix}[calculator_type]" %>
		<%= label_tag field_name, t(:calculator) %>
		<%= select_tag field_name,
									 options_from_collection_for_select(@calculators, :to_s, :description, promotion_action.calculator.type),
									 :class => 'type-select' %>
		<% if promotion_action.calculator.respond_to?(:preferences) %>
			&nbsp; <span class="warning"><%= t(:calculator_settings_warning) %></span>
		<% end %>
	</p>

	<% unless promotion_action.new_record? %>
		<div class="settings">
			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_flat_percent]",
										t("preferred_flat_percent") %>
			<%= text_field_tag "#{param_prefix}[calculator_attributes][preferred_flat_percent]",
													promotion_action.calculator.get_preference(:flat_percent),
													:size => 10 %>

			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_taxon]",
										t("preferred_taxon") %>
			<%= select_tag 	"#{param_prefix}[calculator_attributes][preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_action.calculator.get_preference(:taxon))  %>
			<%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
		</div>
	<% end %>

</div>

app/views/spree/admin/promotions/actions/_flat_rate_per_taxon.html.erb
<div class="calculator-fields">

	<p class="field">
		<% field_name = "#{param_prefix}[calculator_type]" %>
		<%= label_tag field_name, t(:calculator) %>
		<%= select_tag field_name,
									 options_from_collection_for_select(@calculators, :to_s, :description, promotion_action.calculator.type),
									 :class => 'type-select' %>
		<% if promotion_action.calculator.respond_to?(:preferences) %>
			&nbsp; <span class="warning"><%= t(:calculator_settings_warning) %></span>
		<% end %>
	</p>

	<% unless promotion_action.new_record? %>
		<div class="settings">
			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_amount]",
										t("preferred_amount") %>
			<%= text_field_tag "#{param_prefix}[calculator_attributes][preferred_amount]",
													promotion_action.calculator.get_preference(:amount),
													:size => 10 %>

			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_taxon]",
										t("preferred_taxon") %>
			<%= select_tag 	"#{param_prefix}[calculator_attributes][preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_action.calculator.get_preference(:taxon))  %>
			<%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
		</div>
	<% end %>

</div>

app/views/spree/admin/promotions/actions/_pay_n_get_m.html.erb
<div class="calculator-fields">

	<p class="field">
		<% field_name = "#{param_prefix}[calculator_type]" %>
		<%= label_tag field_name, t(:calculator) %>
		<%= select_tag field_name,
									 options_from_collection_for_select(@calculators, :to_s, :description, promotion_action.calculator.type),
									 :class => 'type-select' %>
		<% if promotion_action.calculator.respond_to?(:preferences) %>
			&nbsp; <span class="warning"><%= t(:calculator_settings_warning) %></span>
		<% end %>
	</p>

	<% unless promotion_action.new_record? %>
		<div class="settings">
			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_to_get]",
										t("preferred_to_get") %>
			<%= text_field_tag "#{param_prefix}[calculator_attributes][preferred_to_get]",
													promotion_action.calculator.get_preference(:to_get),
													:size => 4 %>

			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_to_pay]",
										t("preferred_to_pay") %>
			<%= text_field_tag "#{param_prefix}[calculator_attributes][preferred_to_pay]",
													promotion_action.calculator.get_preference(:to_pay),
													:size => 4 %>

			<%= label_tag "#{param_prefix}[calculator_attributes][preferred_taxon]",
										t("preferred_taxon") %>
			<%= select_tag 	"#{param_prefix}[calculator_attributes][preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_action.calculator.get_preference(:taxon))  %>
			<%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
		</div>
	<% end %>

</div>

app/views/spree/admin/promotions/rules/_club.html.erb
<p class="field"><%= label_tag nil, t('promotion_rule_types.club.description') %></p>

app/views/spree/admin/promotions/rules/_gender.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_gender" %>">
  	<%= select_tag 	"#{param_prefix}[preferred_gender]", 
  									"<option value='m'>#{t(:male)}</option><option value='f'>#{t(:female)}</option>".html_safe %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_happy_birthday.html.erb
<p class="field"><%= label_tag nil, t('promotion_rule_types.happy_birthday.description') %></p>

app/views/spree/admin/promotions/rules/_item_quantity.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_amount" %>">
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Spree::Promotion::Rules::ItemQuantity::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator), :class => "select2 fullwidth" %>
    <%= text_field_tag "#{param_prefix}[preferred_quantity]", promotion_rule.preferred_quantity, :size => 10 %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_order_quantity.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_amount" %>">
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Spree::Promotion::Rules::OrderQuantity::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator) %>
    <%= text_field_tag "#{param_prefix}[preferred_quantity]", promotion_rule.preferred_quantity, :size => 10 %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_order_total.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_amount" %>">
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Spree::Promotion::Rules::ProductBuyTaxonTotal::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator) %>
    <%= text_field_tag "#{param_prefix}[preferred_amount]", promotion_rule.preferred_amount, :size => 10 %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_product_buy_taxon.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_taxon" %>">
    <%= "Taxon" %>
    <%= select_tag 	"#{param_prefix}[preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_rule.preferred_taxon), :class => "select2 fullwidth"  %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_product_buy_taxon_quantity.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_quantity" %>">
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Spree::Promotion::Rules::ProductBuyTaxonQuantity::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator) %>
    <%= text_field_tag "#{param_prefix}[preferred_quantity]", promotion_rule.preferred_quantity, :size => 10 %>
  </label>

  <label for="<%= "#{param_prefix}_preferred_taxon" %>">
    <%= "Taxon" %>
    <%= select_tag 	"#{param_prefix}[preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_rule.preferred_taxon), :class => "select2 fullwidth"  %>
  </label>
</p>

app/views/spree/admin/promotions/rules/_product_buy_taxon_total.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_amount" %>">
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Spree::Promotion::Rules::ProductBuyTaxonTotal::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator) %>
    <%= text_field_tag "#{param_prefix}[preferred_amount]", promotion_rule.preferred_amount, :size => 10 %>
  </label>

  <label for="<%= "#{param_prefix}_preferred_taxon" %>">
    <%= "Taxon" %>
    <%= select_tag 	"#{param_prefix}[preferred_taxon]",
     								options_for_select(Spree::Taxon.all.collect{ |t| [t.name_for_select, t.id] }, promotion_rule.preferred_taxon), :class => "select2 fullwidth"  %>
  </label>
</p>

app/views/spree/admin/shared/_promotions_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_promotions_sub_tabs">
    <%= tab :promotions %>
    <%= tab :code_groups %>
  </ul>
<% end %>